mongodb:
  replicaSet:
    enabled: true
  image:
    tag: "4.2.7"    
  usePassword: false
  auth:
    enabled: false
  architecture: replicaset
  serviceAccount:
    create: false    
  persistence:
    enabled: true
  resources:
    requests:
      cpu: 1
      memory: 1Gi
    limits:
      cpu: 2
      memory: 2Gi    