{{- range splitList "," (include "nuxeo.nodeTypes" .) }}
{{- $nxNodeType := . -}}
{{- with $ }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "nuxeo.fullname" . }}-{{ $nxNodeType }}
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  selector:
    matchLabels:
      draft: {{ default "draft-app" .Values.draft }}      
      app: {{ template "nuxeo.fullname" . }}
      nuxeoNode: {{ template "nuxeo.fullname" . }}-{{ $nxNodeType }}
{{- if or (eq $nxNodeType "api") (eq $nxNodeType "single") }}
  replicas: {{ .Values.replicaCount }}
{{- else }}
  replicas: {{ .Values.workerCount }}
{{- end }}
  template:
    metadata:
      labels:
        draft: {{ default "draft-app" .Values.draft }}
        app: {{ template "nuxeo.fullname" . }}
        nuxeoNode: {{ template "nuxeo.fullname" . }}-{{ $nxNodeType }}
{{- if or (eq $nxNodeType "api") (eq $nxNodeType "single") }}
        tier: frontend
{{- else }}
        tier: backend
{{- end }}

{{- with .Values.podLabels }}
{{ toYaml . | indent 8 }}
{{- end }}
{{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
    spec:
{{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.image.pullSecrets }}
{{- end }}
      containers:
      - name: {{ .Chart.Name }}
        resources:
          requests:
            memory: "{{ .Values.resources.requests.memory }}"
            cpu: "{{ .Values.resources.requests.cpu }}"
          limits:
            memory: "{{ .Values.resources.limits.memory }}"
            cpu: "{{ .Values.resources.limits.cpu }}"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
{{- if .Values.image.pullPolicy }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
{{- end}}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        livenessProbe:
          httpGet:
            path: {{ .Values.probePath }}
            port: {{ .Values.service.internalPort }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          successThreshold: {{ .Values.livenessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
        readinessProbe:
          httpGet:
            path: {{ .Values.probePath }}
            port: {{ .Values.service.internalPort }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          successThreshold: {{ .Values.readinessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
        env:
{{- if .Values.clid }}
        - name: NUXEO_CLID
          valueFrom:
            secretKeyRef:
              name: {{ template "nuxeo.fullname" . }}-instance-clid
              key: CLID
{{- end }}
        - name: NUXEO_PACKAGES
          value: {{ .Values.packages }}
{{- if .Values.customEnvs }}
{{ toYaml .Values.customEnvs | indent 8 }}
{{- end }}
        envFrom:
{{- if .Values.customEnvsFrom }}
{{ toYaml .Values.customEnvsFrom | indent 8 }}
{{- end }}
        volumeMounts:
          - name: nuxeoconf
            mountPath: /etc/nuxeo/conf.d/
{{- if (not .Values.googleCloudStorage.enabled)}}
          - name: binaries
            mountPath: /var/lib/nuxeo/binaries
{{- end }}
          - name: log
            mountPath: /var/log/nuxeo
          - name: gcpcconfig
            mountPath: /opt/nuxeo/gcp
      initContainers:
{{- if or .Values.elasticsearch.deploy .Values.elasticsearch.enabled }}
      - name: init-elasticsearch
        image: busybox
        command: ['sh', '-c', 'until nc -w1 {{ .Values.elasticsearch.server }} {{ .Values.elasticsearch.port }}; do echo "waiting for elastic"; sleep 2; done;']
{{- end }}
{{- if or .Values.mongodb.deploy .Values.mongodb.enabled }}
      - name: init-mongodb
        image: busybox
        command: ['sh', '-c', 'until nc -w1 {{ .Values.mongodb.server }} {{ .Values.mongodb.port }}; do echo "waiting for mongodb"; sleep 2; done;']
{{- end }}
{{- if or .Values.postgresql.deploy .Values.postgresql.enabled }}
      - name: init-postgresql
        image: busybox
        command: ['sh', '-c', 'until nc -w1 {{ .Release.Name }}-postgresql 5432; do echo "waiting for postgresql"; sleep 2; done;']
{{- end }}
{{- if or .Values.kafka.deploy .Values.kafka.enabled}}
      - name: init-kafka
        image: busybox
        command: ['sh', '-c', 'until nc -w1 {{ .Values.kafka.server }} {{ .Values.kafka.port }}; do echo "waiting for kafka"; sleep 2; done;']
{{- end }}
      securityContext:
        fsGroup: 1000
      volumes:
      - name: nuxeoconf
        configMap:
          name: {{ template "nuxeo.fullname" . }}-conf-{{ $nxNodeType }}
        {{- if (not .Values.googleCloudStorage.enabled)}}
      - name: binaries
        emptyDir: {}
        {{- end }}
      - name: log
        {{- if .Values.logs.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "nuxeo.fullname" . }}-log
        {{- else }}
        emptyDir: {}
        {{- end }}
      - name: gcpcconfig
        secret:
          secretName: {{ template "nuxeo.fullname" . }}-gcp-sa
{{- end }}
{{- end }}