{{- if and .Values.enable .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "nuxeo.fullname" . }}
  labels:
    app: {{ template "nuxeo.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
  - host: {{ template "nuxeo.name" . }}.nxtest
    http:
      paths:
      - backend:
          serviceName: {{ template "nuxeo.fullname" . }}
          servicePort: {{ .Values.service.externalPort}}
{{- end -}}