{{- if .Values.clid }}
{{ $clidStringData:= printf "CLID: %s" (.Values.clid | quote) }}
{{ template "nuxeo.secret" (merge (dict "key" "instance-clid" "val" $clidStringData ) .) }}
{{- end }}
{{- range $key, $val := .Values.extraSecrets }}
{{ with $ }}
---
{{ template "nuxeo.secret" (merge (dict "key" $key "val" $val) .) }}
{{- end }}
{{- end }}
{{- if .Values.gcpb64 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "nuxeo.fullname" . }}-gcp-sa
  labels:
    app: {{ template "nuxeo.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  gcp-credentials.json: {{ .Values.gcpb64 }}
{{- end }}    
