{{- if and .Values.nuxeo.enable .Values.nuxeo.clid }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "nuxeo.fullname" . }}-instance-clid
  namespace: {{ .Values.nuxeo.tenantId }}
  labels:
    app: {{ template "nuxeo.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
  CLID: {{ .Values.nuxeo.clid }}
{{- end }}
