apiVersion: v1
kind: Service
metadata:
  name: {{ template "nuxeo.fullname" . }}-{{ .Values.nuxeo.tenantId }}
  namespace: {{ .Values.nuxeo.tenantId }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
{{- with .Values.nuxeo.service.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- if .Values.nuxeo.service.annotations }}
  annotations:
{{ toYaml .Values.nuxeo.service.annotations | indent 4 }}
{{- end }}
    fabric8.io/ingress.annotations: 'kubernetes.io/ingress.class: "nginx"\nnginx.ingress.kubernetes.io/affinity: "cookie"\nnginx.ingress.kubernetes.io/affinity-mode: "persistent"\nnginx.ingress.kubernetes.io/session-cookie-name: "nxaffinity"'
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/affinity-mode: persistent
spec:
  type: {{ .Values.nuxeo.service.type }}
  ports:
  - port: {{ .Values.nuxeo.service.externalPort }}
    targetPort: {{ .Values.nuxeo.service.internalPort }}
    protocol: TCP
    name: http
  selector:
    app: {{ template "nuxeo.fullname" . }}-{{ .Values.nuxeo.tenantId }}

