nameOverride: company-a
architecture: api-worker
ingress:
  hostname: company-a.multitenant.nuxeo.com
  tls: 
    - hosts:
      - company-a.multitenant.nuxeo.com
      secretName: static-wildcard-tls
customProperties:
  tenant: |
    nuxeo.tenantId=company-a
    # k8s_pod vs k8s_container vs default
    nuxeo.stackdriver.forceResourceType=k8s_pod
    metrics.streams.enabled=true
extraVolumes:
  - name: gcpcconfig
    secret:
      secretName: nuxeo-company-a-gcp-sa
