packages: 
enable: true
architecture: singleNode
image:
  repository: gcr.io/jx-preprod/nuxeo-mt
enable: true
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/affinity-mode: persistent
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
replicaCount: 2
workerCount: 1
metrics:
  enabled: true
  stackdriver:
    enabled: false
mongodb:
  enabled: true
  host: nuxeo-mongodb-headless.nx-shared-storage.svc.cluster.local
  credentials: root:TEwlJu2W1Z
  protocol: mongodb
  port: 27017
elasticsearch:
  enabled: true
  host: elasticsearch-master.nx-shared-storage.svc.cluster.local
  protocol: http
  port: 9200
kafka:
  enabled: true
  host: nuxeo-kafka.nx-shared-storage.svc.cluster.local
  port: 9092
googleCloudStorage:
  enabled: true
  project: "jx-preprod"
  credentials: /opt/nuxeo/gcp/gcp-credentials.json
  bucket: "nuxeo-multitenant-storage-bucket"