nameOverride: company-b
ingress:
  hostname: company-b.multitenant.nuxeo.com
customProperties:
  tenant: |
    nuxeo.tenantId=company-b
    # k8s_pod vs k8s_container vs default
    nuxeo.stackdriver.forceResourceType=k8s_pod
    metrics.streams.enabled=true
extraVolumes:
  - name: gcpcconfig
    secret:
      secretName: nuxeo-company-b-gcp-sa
